defaults:
  - embedder: litellm_opt_template
  - providers: unstructured_opt_template
  - vector_store: chroma
  - rephraser: noop
  - reranker: noop
  - answer_data_source: corpus
  - _self_

type: ragbits.evaluate.pipelines.document_search:DocumentSearchWithIngestionPipeline
ingest: true

