defaults:
  - vector_store@config.vector_store: chroma
  - rephraser@config.rephraser: noop
  - reranker@config.reranker: noop
  - providers@config.providers: unstructured
  - source@config.source: hf
  - _self_

type: ragbits.evaluate.pipelines.document_search:DocumentSearchPipeline
