name: Deploy documentation

on:
  push:
    branches: [chore/setup_docs]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    environment: documentation
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.10"
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Deploy docs
        run: ./.github/scripts/deploy_docs.sh
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}

